Repository LeonardoDecaris/TechAcademy7, pull requests merged in 2025-08, with the labels that each got.

#9 Back end docker compose
  Nginx/Dockerfile
  Nginx/nginx.conf
  backEnd/Dockerfile
  backEnd/package-lock.json
  backEnd/package.json
  backEnd/src/app.ts
  backEnd/src/config/database.ts
  backEnd/src/controllers/caminhoneiro.controller.ts
  backEnd/src/controllers/carga.controller.ts
  backEnd/src/controllers/empresa.controller.ts
  backEnd/src/controllers/frete.controller.ts
  backEnd/src/controllers/imagem_caminhao.controller.ts
  backEnd/src/controllers/imagem_carga.controller.ts
  backEnd/src/controllers/imagem_empresa.controller.ts
  backEnd/src/controllers/imagem_usuario.controller.ts
  backEnd/src/controllers/login.controller.ts
  backEnd/src/controllers/status.controller.ts
  backEnd/src/controllers/tipo_carga.controller.ts
  backEnd/src/controllers/usuario.controller.ts
  backEnd/src/controllers/veiculo.controller.ts
  backEnd/src/controllers/veiculo_tipoCarga.controller.ts
  backEnd/src/index.ts
  backEnd/src/middleware/authMiddleware.ts
  backEnd/src/middleware/uploadMiddleware.ts
  backEnd/src/models/caminhoneiro.model.ts
  backEnd/src/models/carga.model.ts
  backEnd/src/models/empresa.model.ts
  backEnd/src/models/frete.model.ts
  backEnd/src/models/imagem.caminhao.model.ts
  backEnd/src/models/imagem_carga.model.ts
  backEnd/src/models/imagem_empresa.model.ts
  backEnd/src/models/imagem_usuario.model.ts
  backEnd/src/models/status.model.ts
  backEnd/src/models/tipo_carga.model.ts
  backEnd/src/models/usuario.model.ts
  backEnd/src/models/veiculo.model.ts
  backEnd/src/models/veiculo_tipoCarga.model.ts
  backEnd/src/routes/caminhoneiro.routes.ts
  backEnd/src/routes/carga.routes.ts
  backEnd/src/routes/empresa.routes.ts
  backEnd/src/routes/frete.routes.ts
  backEnd/src/routes/imagem_caminhao.routes.ts
  backEnd/src/routes/imagem_carga.routes.ts
  backEnd/src/routes/imagem_empresa.routes.ts
  backEnd/src/routes/imagem_usuario.routes.ts
  backEnd/src/routes/login.routes.ts
  backEnd/src/routes/status.routes.ts
  backEnd/src/routes/tipo_carga.routes.ts
  backEnd/src/routes/usuario.routes.ts
  backEnd/src/routes/veiculo.routes.ts
  backEnd/src/routes/veiculo_tipoCarga.routes.ts
  backEnd/src/swagger.yaml
  backEnd/src/types/index.ts
  backEnd/src/utils/itemUtils.ts
  backEnd/src/utils/jtw.ts
  docker-compose.yml
Labels: enhancement

#11 feat(auteticacao): correcao da atutheticacao do usuario
  App/src/context/AuthContext.tsx
  App/src/hooks/get/GetDadosHome.ts
  App/src/hooks/get/GetDadosUsuario.ts
  App/src/hooks/post/loginUsuario.ts
  App/src/screens/private/Home.tsx
  App/src/screens/public/Cadastro.tsx
  App/src/screens/public/Login.tsx
  App/src/utils/Validacao.ts
  App/src/utils/funcoes.ts
Labels: bug, enhancement, invalid

#19 feature(Editar Perfil, e sistema de login)
  App/src/assets/image/Caminhão.png
  App/src/assets/image/image.png
  App/src/components/cards/CardCaminhao.tsx
  App/src/components/cards/CardGarca.tsx
  App/src/components/cards/CardVeiculo.tsx
  App/src/components/form/InputAuth.tsx
  App/src/hooks/get/GetDadosVeiculo.ts
  App/src/hooks/post/cadastroVeiculo.ts
  App/src/hooks/post/esqueciSenha.ts
  App/src/hooks/post/loginUsuario.ts
  App/src/hooks/post/solicitarNovasenha.ts
  App/src/hooks/put/EditarUsuario.ts
  App/src/navigation/MainTabs.tsx
  App/src/navigation/Routes.tsx
  App/src/screens/private/EditarPerfil.tsx
  App/src/screens/private/Home.tsx
  App/src/screens/private/Perfil.tsx
  App/src/screens/public/Cadastro.tsx
  App/src/screens/public/Login.tsx
  App/src/screens/public/NovaSenha.tsx
  App/src/screens/public/SolicitarNovaSenha.tsx
  backEnd/package-lock.json
  backEnd/package.json
  backEnd/src/controllers/authController.ts
  backEnd/src/controllers/usuario.controller.ts
  backEnd/src/controllers/veiculo.controller.ts
  backEnd/src/models/index.ts
  backEnd/src/routes/usuario.routes.ts
  backEnd/src/routes/veiculo.routes.ts
Labels: bug, documentation, enhancement
